@startuml
title ActivityDiagram

start
:Open App;
:Main Table View;
repeat
  :Choose Action;
  if (Add Record?) then (Yes)
    :Fill Record Form;
    :Save to Table;
  elseif (Edit Record?) then (Yes)
    :Select Record;
    :Modify Data;
    :Update Table;
  elseif (Filter Data?) then (Yes)
    :Set Filters;
    :Apply to Table;
  endif
repeat while (Continue?) 
:Export Data;
stop
@enduml