@startuml
title ActivityDiagram

start
:Пользователь входит в приложение;
if (Новый пользователь?) then (Да)
  :Регистрация;
  :Создание первого счета;
else (Нет)
  :Авторизация;
endif

:Открывается главный экран;
repeat
  :Выбор действия;
  if (Добавить транзакцию?) then (Да)
    :Ввод суммы;
    :Выбор категории;
    :Сохранение транзакции;
    :Обновление баланса;
  elseif (Просмотр отчетов?) then (Да)
    :Выбор периода;
    :Формирование графиков;
    :Отображение статистики;
  elseif (Управление бюджетом?) then (Да)
    :Установка лимитов;
    :Отслеживание расходов;
  endif
repeat while (Продолжить работу?) 
stop
@enduml